--changeset fineract:1:insertDefaultServerConnection
INSERT INTO tenant_server_connections VALUES (1,'localhost','fineract_default','5432','mifosadmin','magic',1,5,30000,1,60,1,50,1,40,20,10,60,34000,60000,0,1,'');

--changeset fineract:2:insertDefaultTenant
INSERT INTO tenants (id,identifier,name,timezone_id,country_id,joined_date,created_date,lastmodified_date,oltp_id,report_id) VALUES (1,'default','Default Demo Tenant','Asia/Kolkata',NULL,NULL,NULL,NULL,1,1);

--changeset fineract:3:insertTimezones
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (1,'AD','Europe/Andorra','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (2,'AE','Asia/Dubai','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (3,'AF','Asia/Kabul','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (4,'AG','America/Antigua','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (5,'AI','America/Anguilla','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (6,'AL','Europe/Tirane','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (7,'AM','Asia/Yerevan','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (8,'AO','Africa/Luanda','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (9,'AQ','Antarctica/McMurdo','McMurdo Station, Ross Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (10,'AQ','Antarctica/South_Pole','Amundsen-Scott Station, South Pole');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (11,'AQ','Antarctica/Rothera','Rothera Station, Adelaide Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (12,'AQ','Antarctica/Palmer','Palmer Station, Anvers Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (13,'AQ','Antarctica/Mawson','Mawson Station, Holme Bay');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (14,'AQ','Antarctica/Davis','Davis Station, Vestfold Hills');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (15,'AQ','Antarctica/Casey','Casey Station, Bailey Peninsula');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (16,'AQ','Antarctica/Vostok','Vostok Station, Lake Vostok');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (17,'AQ','Antarctica/DumontDUrville','Dumont-dUrville Station, Terre Adelie');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (18,'AQ','Antarctica/Syowa','Syowa Station, E Ongul I');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (19,'AQ','Antarctica/Macquarie','Macquarie Island Station, Macquarie Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (20,'AR','America/Argentina/Buenos_Aires','Buenos Aires (BA, CF)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (21,'AR','America/Argentina/Cordoba','most locations (CB, CC, CN, ER, FM, MN, SE, SF)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (22,'AR','America/Argentina/Salta','(SA, LP, NQ, RN)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (23,'AR','America/Argentina/Jujuy','Jujuy (JY)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (24,'AR','America/Argentina/Tucuman','Tucuman (TM)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (25,'AR','America/Argentina/Catamarca','Catamarca (CT), Chubut (CH)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (26,'AR','America/Argentina/La_Rioja','La Rioja (LR)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (27,'AR','America/Argentina/San_Juan','San Juan (SJ)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (28,'AR','America/Argentina/Mendoza','Mendoza (MZ)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (29,'AR','America/Argentina/San_Luis','San Luis (SL)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (30,'AR','America/Argentina/Rio_Gallegos','Santa Cruz (SC)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (31,'AR','America/Argentina/Ushuaia','Tierra del Fuego (TF)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (32,'AS','Pacific/Pago_Pago','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (33,'AT','Europe/Vienna','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (34,'AU','Australia/Lord_Howe','Lord Howe Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (35,'AU','Australia/Hobart','Tasmania - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (36,'AU','Australia/Currie','Tasmania - King Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (37,'AU','Australia/Melbourne','Victoria');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (38,'AU','Australia/Sydney','New South Wales - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (39,'AU','Australia/Broken_Hill','New South Wales - Yancowinna');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (40,'AU','Australia/Brisbane','Queensland - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (41,'AU','Australia/Lindeman','Queensland - Holiday Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (42,'AU','Australia/Adelaide','South Australia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (43,'AU','Australia/Darwin','Northern Territory');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (44,'AU','Australia/Perth','Western Australia - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (45,'AU','Australia/Eucla','Western Australia - Eucla area');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (46,'AW','America/Aruba','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (47,'AX','Europe/Mariehamn','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (48,'AZ','Asia/Baku','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (49,'BA','Europe/Sarajevo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (50,'BB','America/Barbados','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (51,'BD','Asia/Dhaka','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (52,'BE','Europe/Brussels','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (53,'BF','Africa/Ouagadougou','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (54,'BG','Europe/Sofia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (55,'BH','Asia/Bahrain','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (56,'BI','Africa/Bujumbura','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (57,'BJ','Africa/Porto-Novo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (58,'BL','America/St_Barthelemy','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (59,'BM','Atlantic/Bermuda','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (60,'BN','Asia/Brunei','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (61,'BO','America/La_Paz','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (62,'BQ','America/Kralendijk','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (63,'BR','America/Noronha','Atlantic islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (64,'BR','America/Belem','Amapa, E Para');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (65,'BR','America/Fortaleza','NE Brazil (MA, PI, CE, RN, PB)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (66,'BR','America/Recife','Pernambuco');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (67,'BR','America/Araguaina','Tocantins');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (68,'BR','America/Maceio','Alagoas, Sergipe');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (69,'BR','America/Bahia','Bahia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (70,'BR','America/Sao_Paulo','S & SE Brazil (GO, DF, MG, ES, RJ, SP, PR, SC, RS)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (71,'BR','America/Campo_Grande','Mato Grosso do Sul');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (72,'BR','America/Cuiaba','Mato Grosso');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (73,'BR','America/Santarem','W Para');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (74,'BR','America/Porto_Velho','Rondonia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (75,'BR','America/Boa_Vista','Roraima');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (76,'BR','America/Manaus','E Amazonas');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (77,'BR','America/Eirunepe','W Amazonas');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (78,'BR','America/Rio_Branco','Acre');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (79,'BS','America/Nassau','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (80,'BT','Asia/Thimphu','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (81,'BW','Africa/Gaborone','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (82,'BY','Europe/Minsk','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (83,'BZ','America/Belize','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (84,'CA','America/St_Johns','Newfoundland Time, including SE Labrador');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (85,'CA','America/Halifax','Atlantic Time - Nova Scotia (most places), PEI');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (86,'CA','America/Glace_Bay','Atlantic Time - Nova Scotia - places that did not observe DST 1966-1971');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (87,'CA','America/Moncton','Atlantic Time - New Brunswick');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (88,'CA','America/Goose_Bay','Atlantic Time - Labrador - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (89,'CA','America/Blanc-Sablon','Atlantic Standard Time - Quebec - Lower North Shore');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (90,'CA','America/Montreal','Eastern Time - Quebec - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (91,'CA','America/Toronto','Eastern Time - Ontario - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (92,'CA','America/Nipigon','Eastern Time - Ontario & Quebec - places that did not observe DST 1967-1973');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (93,'CA','America/Thunder_Bay','Eastern Time - Thunder Bay, Ontario');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (94,'CA','America/Iqaluit','Eastern Time - east Nunavut - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (95,'CA','America/Pangnirtung','Eastern Time - Pangnirtung, Nunavut');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (96,'CA','America/Resolute','Central Standard Time - Resolute, Nunavut');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (97,'CA','America/Atikokan','Eastern Standard Time - Atikokan, Ontario and Southampton I, Nunavut');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (98,'CA','America/Rankin_Inlet','Central Time - central Nunavut');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (99,'CA','America/Winnipeg','Central Time - Manitoba & west Ontario');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (100,'CA','America/Rainy_River','Central Time - Rainy River & Fort Frances, Ontario');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (101,'CA','America/Regina','Central Standard Time - Saskatchewan - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (102,'CA','America/Swift_Current','Central Standard Time - Saskatchewan - midwest');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (103,'CA','America/Edmonton','Mountain Time - Alberta, east British Columbia & west Saskatchewan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (104,'CA','America/Cambridge_Bay','Mountain Time - west Nunavut');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (105,'CA','America/Yellowknife','Mountain Time - central Northwest Territories');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (106,'CA','America/Inuvik','Mountain Time - west Northwest Territories');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (107,'CA','America/Creston','Mountain Standard Time - Creston, British Columbia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (108,'CA','America/Dawson_Creek','Mountain Standard Time - Dawson Creek & Fort Saint John, British Columbia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (109,'CA','America/Vancouver','Pacific Time - west British Columbia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (110,'CA','America/Whitehorse','Pacific Time - south Yukon');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (111,'CA','America/Dawson','Pacific Time - north Yukon');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (112,'CC','Indian/Cocos','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (113,'CD','Africa/Kinshasa','west Dem. Rep. of Congo');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (114,'CD','Africa/Lubumbashi','east Dem. Rep. of Congo');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (115,'CF','Africa/Bangui','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (116,'CG','Africa/Brazzaville','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (117,'CH','Europe/Zurich','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (118,'CI','Africa/Abidjan','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (119,'CK','Pacific/Rarotonga','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (120,'CL','America/Santiago','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (121,'CL','Pacific/Easter','Easter Island & Sala y Gomez');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (122,'CM','Africa/Douala','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (123,'CN','Asia/Shanghai','east China - Beijing, Guangdong, Shanghai, etc.');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (124,'CN','Asia/Harbin','Heilongjiang (except Mohe), Jilin');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (125,'CN','Asia/Chongqing','central China - Sichuan, Yunnan, Guangxi, Shaanxi, Guizhou, etc.');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (126,'CN','Asia/Urumqi','most of Tibet & Xinjiang');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (127,'CN','Asia/Kashgar','west Tibet & Xinjiang');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (128,'CO','America/Bogota','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (129,'CR','America/Costa_Rica','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (130,'CU','America/Havana','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (131,'CV','Atlantic/Cape_Verde','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (132,'CW','America/Curacao','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (133,'CX','Indian/Christmas','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (134,'CY','Asia/Nicosia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (135,'CZ','Europe/Prague','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (136,'DE','Europe/Berlin','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (137,'DJ','Africa/Djibouti','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (138,'DK','Europe/Copenhagen','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (139,'DM','America/Dominica','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (140,'DO','America/Santo_Domingo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (141,'DZ','Africa/Algiers','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (142,'EC','America/Guayaquil','mainland');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (143,'EC','Pacific/Galapagos','Galapagos Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (144,'EE','Europe/Tallinn','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (145,'EG','Africa/Cairo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (146,'EH','Africa/El_Aaiun','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (147,'ER','Africa/Asmara','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (148,'ES','Europe/Madrid','mainland');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (149,'ES','Africa/Ceuta','Ceuta & Melilla');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (150,'ES','Atlantic/Canary','Canary Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (151,'ET','Africa/Addis_Ababa','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (152,'FI','Europe/Helsinki','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (153,'FJ','Pacific/Fiji','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (154,'FK','Atlantic/Stanley','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (155,'FM','Pacific/Chuuk','Chuuk (Truk) and Yap');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (156,'FM','Pacific/Pohnpei','Pohnpei (Ponape)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (157,'FM','Pacific/Kosrae','Kosrae');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (158,'FO','Atlantic/Faroe','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (159,'FR','Europe/Paris','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (160,'GA','Africa/Libreville','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (161,'GB','Europe/London','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (162,'GD','America/Grenada','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (163,'GE','Asia/Tbilisi','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (164,'GF','America/Cayenne','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (165,'GG','Europe/Guernsey','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (166,'GH','Africa/Accra','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (167,'GI','Europe/Gibraltar','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (168,'GL','America/Godthab','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (169,'GL','America/Danmarkshavn','east coast, north of Scoresbysund');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (170,'GL','America/Scoresbysund','Scoresbysund / Ittoqqortoormiit');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (171,'GL','America/Thule','Thule / Pituffik');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (172,'GM','Africa/Banjul','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (173,'GN','Africa/Conakry','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (174,'GP','America/Guadeloupe','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (175,'GQ','Africa/Malabo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (176,'GR','Europe/Athens','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (177,'GS','Atlantic/South_Georgia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (178,'GT','America/Guatemala','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (179,'GU','Pacific/Guam','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (180,'GW','Africa/Bissau','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (181,'GY','America/Guyana','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (182,'HK','Asia/Hong_Kong','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (183,'HN','America/Tegucigalpa','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (184,'HR','Europe/Zagreb','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (185,'HT','America/Port-au-Prince','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (186,'HU','Europe/Budapest','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (187,'ID','Asia/Jakarta','Java & Sumatra');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (188,'ID','Asia/Pontianak','west & central Borneo');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (189,'ID','Asia/Makassar','east & south Borneo, Sulawesi (Celebes), Bali, Nusa Tengarra, west Timor');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (190,'ID','Asia/Jayapura','west New Guinea (Irian Jaya) & Malukus (Moluccas)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (191,'IE','Europe/Dublin','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (192,'IL','Asia/Jerusalem','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (193,'IM','Europe/Isle_of_Man','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (194,'IN','Asia/Kolkata','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (195,'IO','Indian/Chagos','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (196,'IQ','Asia/Baghdad','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (197,'IR','Asia/Tehran','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (198,'IS','Atlantic/Reykjavik','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (199,'IT','Europe/Rome','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (200,'JE','Europe/Jersey','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (201,'JM','America/Jamaica','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (202,'JO','Asia/Amman','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (203,'JP','Asia/Tokyo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (204,'KE','Africa/Nairobi','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (205,'KG','Asia/Bishkek','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (206,'KH','Asia/Phnom_Penh','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (207,'KI','Pacific/Tarawa','Gilbert Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (208,'KI','Pacific/Enderbury','Phoenix Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (209,'KI','Pacific/Kiritimati','Line Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (210,'KM','Indian/Comoro','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (211,'KN','America/St_Kitts','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (212,'KP','Asia/Pyongyang','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (213,'KR','Asia/Seoul','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (214,'KW','Asia/Kuwait','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (215,'KY','America/Cayman','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (216,'KZ','Asia/Almaty','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (217,'KZ','Asia/Qyzylorda','Qyzylorda (Kyzylorda, Kzyl-Orda)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (218,'KZ','Asia/Aqtobe','Aqtobe (Aktobe)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (219,'KZ','Asia/Aqtau','Atyrau (Atirau, Guryev), Mangghystau (Mankistau)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (220,'KZ','Asia/Oral','West Kazakhstan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (221,'LA','Asia/Vientiane','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (222,'LB','Asia/Beirut','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (223,'LC','America/St_Lucia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (224,'LI','Europe/Vaduz','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (225,'LK','Asia/Colombo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (226,'LR','Africa/Monrovia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (227,'LS','Africa/Maseru','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (228,'LT','Europe/Vilnius','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (229,'LU','Europe/Luxembourg','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (230,'LV','Europe/Riga','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (231,'LY','Africa/Tripoli','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (232,'MA','Africa/Casablanca','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (233,'MC','Europe/Monaco','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (234,'MD','Europe/Chisinau','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (235,'ME','Europe/Podgorica','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (236,'MF','America/Marigot','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (237,'MG','Indian/Antananarivo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (238,'MH','Pacific/Majuro','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (239,'MH','Pacific/Kwajalein','Kwajalein');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (240,'MK','Europe/Skopje','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (241,'ML','Africa/Bamako','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (242,'MM','Asia/Rangoon','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (243,'MN','Asia/Ulaanbaatar','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (244,'MN','Asia/Hovd','Bayan-Olgiy, Govi-Altai, Hovd, Uvs, Zavkhan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (245,'MN','Asia/Choibalsan','Dornod, Sukhbaatar');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (246,'MO','Asia/Macau','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (247,'MP','Pacific/Saipan','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (248,'MQ','America/Martinique','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (249,'MR','Africa/Nouakchott','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (250,'MS','America/Montserrat','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (251,'MT','Europe/Malta','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (252,'MU','Indian/Mauritius','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (253,'MV','Indian/Maldives','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (254,'MW','Africa/Blantyre','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (255,'MX','America/Mexico_City','Central Time - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (256,'MX','America/Cancun','Central Time - Quintana Roo');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (257,'MX','America/Merida','Central Time - Campeche, Yucatan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (258,'MX','America/Monterrey','Mexican Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas away from US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (259,'MX','America/Matamoros','US Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas near US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (260,'MX','America/Mazatlan','Mountain Time - S Baja, Nayarit, Sinaloa');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (261,'MX','America/Chihuahua','Mexican Mountain Time - Chihuahua away from US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (262,'MX','America/Ojinaga','US Mountain Time - Chihuahua near US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (263,'MX','America/Hermosillo','Mountain Standard Time - Sonora');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (264,'MX','America/Tijuana','US Pacific Time - Baja California near US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (265,'MX','America/Santa_Isabel','Mexican Pacific Time - Baja California away from US border');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (266,'MX','America/Bahia_Banderas','Mexican Central Time - Bahia de Banderas');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (267,'MY','Asia/Kuala_Lumpur','peninsular Malaysia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (268,'MY','Asia/Kuching','Sabah & Sarawak');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (269,'MZ','Africa/Maputo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (270,'NA','Africa/Windhoek','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (271,'NC','Pacific/Noumea','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (272,'NE','Africa/Niamey','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (273,'NF','Pacific/Norfolk','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (274,'NG','Africa/Lagos','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (275,'NI','America/Managua','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (276,'NL','Europe/Amsterdam','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (277,'NO','Europe/Oslo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (278,'NP','Asia/Kathmandu','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (279,'NR','Pacific/Nauru','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (280,'NU','Pacific/Niue','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (281,'NZ','Pacific/Auckland','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (282,'NZ','Pacific/Chatham','Chatham Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (283,'OM','Asia/Muscat','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (284,'PA','America/Panama','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (285,'PE','America/Lima','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (286,'PF','Pacific/Tahiti','Society Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (287,'PF','Pacific/Marquesas','Marquesas Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (288,'PF','Pacific/Gambier','Gambier Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (289,'PG','Pacific/Port_Moresby','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (290,'PH','Asia/Manila','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (291,'PK','Asia/Karachi','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (292,'PL','Europe/Warsaw','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (293,'PM','America/Miquelon','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (294,'PN','Pacific/Pitcairn','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (295,'PR','America/Puerto_Rico','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (296,'PS','Asia/Gaza','Gaza Strip');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (297,'PS','Asia/Hebron','West Bank');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (298,'PT','Europe/Lisbon','mainland');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (299,'PT','Atlantic/Madeira','Madeira Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (300,'PT','Atlantic/Azores','Azores');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (301,'PW','Pacific/Palau','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (302,'PY','America/Asuncion','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (303,'QA','Asia/Qatar','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (304,'RE','Indian/Reunion','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (305,'RO','Europe/Bucharest','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (306,'RS','Europe/Belgrade','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (307,'RU','Europe/Kaliningrad','Moscow-01 - Kaliningrad');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (308,'RU','Europe/Moscow','Moscow+00 - west Russia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (309,'RU','Europe/Volgograd','Moscow+00 - Caspian Sea');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (310,'RU','Europe/Samara','Moscow+00 - Samara, Udmurtia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (311,'RU','Asia/Yekaterinburg','Moscow+02 - Urals');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (312,'RU','Asia/Omsk','Moscow+03 - west Siberia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (313,'RU','Asia/Novosibirsk','Moscow+03 - Novosibirsk');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (314,'RU','Asia/Novokuznetsk','Moscow+03 - Novokuznetsk');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (315,'RU','Asia/Krasnoyarsk','Moscow+04 - Yenisei River');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (316,'RU','Asia/Irkutsk','Moscow+05 - Lake Baikal');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (317,'RU','Asia/Yakutsk','Moscow+06 - Lena River');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (318,'RU','Asia/Vladivostok','Moscow+07 - Amur River');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (319,'RU','Asia/Sakhalin','Moscow+07 - Sakhalin Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (320,'RU','Asia/Magadan','Moscow+08 - Magadan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (321,'RU','Asia/Kamchatka','Moscow+08 - Kamchatka');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (322,'RU','Asia/Anadyr','Moscow+08 - Bering Sea');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (323,'RW','Africa/Kigali','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (324,'SA','Asia/Riyadh','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (325,'SB','Pacific/Guadalcanal','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (326,'SC','Indian/Mahe','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (327,'SD','Africa/Khartoum','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (328,'SE','Europe/Stockholm','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (329,'SG','Asia/Singapore','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (330,'SH','Atlantic/St_Helena','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (331,'SI','Europe/Ljubljana','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (332,'SJ','Arctic/Longyearbyen','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (333,'SK','Europe/Bratislava','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (334,'SL','Africa/Freetown','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (335,'SM','Europe/San_Marino','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (336,'SN','Africa/Dakar','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (337,'SO','Africa/Mogadishu','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (338,'SR','America/Paramaribo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (339,'SS','Africa/Juba','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (340,'ST','Africa/Sao_Tome','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (341,'SV','America/El_Salvador','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (342,'SX','America/Lower_Princes','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (343,'SY','Asia/Damascus','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (344,'SZ','Africa/Mbabane','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (345,'TC','America/Grand_Turk','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (346,'TD','Africa/Ndjamena','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (347,'TF','Indian/Kerguelen','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (348,'TG','Africa/Lome','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (349,'TH','Asia/Bangkok','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (350,'TJ','Asia/Dushanbe','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (351,'TK','Pacific/Fakaofo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (352,'TL','Asia/Dili','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (353,'TM','Asia/Ashgabat','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (354,'TN','Africa/Tunis','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (355,'TO','Pacific/Tongatapu','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (356,'TR','Europe/Istanbul','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (357,'TT','America/Port_of_Spain','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (358,'TV','Pacific/Funafuti','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (359,'TW','Asia/Taipei','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (360,'TZ','Africa/Dar_es_Salaam','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (361,'UA','Europe/Kiev','most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (362,'UA','Europe/Uzhgorod','Ruthenia');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (363,'UA','Europe/Zaporozhye','Zaporozhye, E Lugansk / Zaporizhia, E Luhansk');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (364,'UA','Europe/Simferopol','central Crimea');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (365,'UG','Africa/Kampala','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (366,'UM','Pacific/Johnston','Johnston Atoll');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (367,'UM','Pacific/Midway','Midway Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (368,'UM','Pacific/Wake','Wake Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (369,'US','America/New_York','Eastern Time');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (370,'US','America/Detroit','Eastern Time - Michigan - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (371,'US','America/Kentucky/Louisville','Eastern Time - Kentucky - Louisville area');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (372,'US','America/Kentucky/Monticello','Eastern Time - Kentucky - Wayne County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (373,'US','America/Indiana/Indianapolis','Eastern Time - Indiana - most locations');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (374,'US','America/Indiana/Vincennes','Eastern Time - Indiana - Daviess, Dubois, Knox & Martin Counties');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (375,'US','America/Indiana/Winamac','Eastern Time - Indiana - Pulaski County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (376,'US','America/Indiana/Marengo','Eastern Time - Indiana - Crawford County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (377,'US','America/Indiana/Petersburg','Eastern Time - Indiana - Pike County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (378,'US','America/Indiana/Vevay','Eastern Time - Indiana - Switzerland County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (379,'US','America/Chicago','Central Time');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (380,'US','America/Indiana/Tell_City','Central Time - Indiana - Perry County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (381,'US','America/Indiana/Knox','Central Time - Indiana - Starke County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (382,'US','America/Menominee','Central Time - Michigan - Dickinson, Gogebic, Iron & Menominee Counties');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (383,'US','America/North_Dakota/Center','Central Time - North Dakota - Oliver County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (384,'US','America/North_Dakota/New_Salem','Central Time - North Dakota - Morton County (except Mandan area)');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (385,'US','America/North_Dakota/Beulah','Central Time - North Dakota - Mercer County');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (386,'US','America/Denver','Mountain Time');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (387,'US','America/Boise','Mountain Time - south Idaho & east Oregon');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (388,'US','America/Shiprock','Mountain Time - Navajo');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (389,'US','America/Phoenix','Mountain Standard Time - Arizona');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (390,'US','America/Los_Angeles','Pacific Time');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (391,'US','America/Anchorage','Alaska Time');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (392,'US','America/Juneau','Alaska Time - Alaska panhandle');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (393,'US','America/Sitka','Alaska Time - southeast Alaska panhandle');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (394,'US','America/Yakutat','Alaska Time - Alaska panhandle neck');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (395,'US','America/Nome','Alaska Time - west Alaska');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (396,'US','America/Adak','Aleutian Islands');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (397,'US','America/Metlakatla','Metlakatla Time - Annette Island');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (398,'US','Pacific/Honolulu','Hawaii');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (399,'UY','America/Montevideo','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (400,'UZ','Asia/Samarkand','west Uzbekistan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (401,'UZ','Asia/Tashkent','east Uzbekistan');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (402,'VA','Europe/Vatican','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (403,'VC','America/St_Vincent','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (404,'VE','America/Caracas','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (405,'VG','America/Tortola','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (406,'VI','America/St_Thomas','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (407,'VN','Asia/Ho_Chi_Minh','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (408,'VU','Pacific/Efate','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (409,'WF','Pacific/Wallis','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (410,'WS','Pacific/Apia','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (411,'YE','Asia/Aden','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (412,'YT','Indian/Mayotte','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (413,'ZA','Africa/Johannesburg','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (414,'ZM','Africa/Lusaka','');
INSERT INTO timezones (id,country_code,timezonename,comments) VALUES (415,'ZW','Africa/Harare','');
