/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
apply plugin: 'org.openapi.generator'
description = 'Fineract Client with Feign'

apply from: 'dependencies.gradle'

openApiMeta {
    generatorName = 'Fineract-Feign'
    packageName = 'org.apache.fineract.client.feign'
    outputFolder = "$buildDir/meta".toString()
}

openApiValidate {
    inputSpec = "file:///$swaggerFile"
    recommend = true
}

tasks.register('buildJavaSdk', org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = 'java'
    library = 'feign'
    verbose = false // Enable verbose output for debugging
    validateSpec = false
    skipValidateSpec = true
    inputSpec = "file:///$swaggerFile"
    outputDir = "$buildDir/generated/temp-java".toString()
    templateDir = "$projectDir/src/main/resources/templates"
    generatorName = 'java'  // Explicitly set the generator
    library = 'feign'      // Explicitly set the library
    
    // Configure the code generation
    groupId = 'org.apache.fineract'
    apiPackage = 'org.apache.fineract.client.services'
    invokerPackage = 'org.apache.fineract.client'
    modelPackage = 'org.apache.fineract.client.models'
    
    // Ensure we're using the correct template version
    templateResourcePath = 'Java/libraries/feign'

    configOptions = [
            dateLibrary                : 'java8',
            java8                      : 'true',
            useRuntimeException        : 'true',
            useBeanValidation          : 'true',
            performBeanValidation      : 'true',
            useGzipFeature             : 'true',
            useTags                    : 'true',
            useClassLevelBeanValidation: 'false',
            useOptional                : 'true',
            serializableModel          : 'true',
            serializationLibrary       : 'jackson',
            library                    : 'feign',
            feignVersion               : '13.6',
            feignApacheHttpClient      : 'true',
            feignJava8                 : 'true',
            useFeign13                 : 'true',
            useFeignGson               : 'false',
            useFeignJackson            : 'true',
            useFeignApacheHttpClient   : 'true'
    ]
}

sourceSets {
    main {
        java {
            srcDirs = [
                "$buildDir/generated/temp-java/src/main/java",
                "$projectDir/src/main/java"
            ]
        }
    }
}

compileJava.dependsOn tasks.buildJavaSdk

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

javadoc {
    options.encoding = 'UTF-8'
}
